import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata = {
  title: "General conditions | Anfa Training",
  description: "Read the general terms and conditions for personal training and bootcamp retreats at Anfa Training.",
};

export default function GeneralConditions() {
  return (
    <>
      <Header />
      <main style={{ paddingTop: "80px" }}>
        <section className="page-banner">
          <div className="container">
            <span style={{ color: "var(--primary)", fontWeight: 700, letterSpacing: "0.1em", textTransform: "uppercase", fontSize: "14px" }}>
              Legal Information
            </span>
            <h1 style={{ marginTop: "8px" }}>General conditions</h1>
            <p>General Terms for Personal Training at Anfa Training.</p>
          </div>
        </section>

        <section style={{ background: "var(--background)", padding: "60px 0" }}>
          <div className="container" style={{ maxWidth: "800px" }}>
            <h3 style={{ fontSize: "20px", color: "var(--primary)", textTransform: "uppercase", marginTop: "24px", marginBottom: "12px" }}>GENERAL TERMS FOR PERSONAL TRAINING AT ANFA TRAINING</h3>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>ANFA TRAINING GENERAL TERMS FOR PERSONAL TRAINING</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Valid from 1.09.2022</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>GENERAL</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>The following conditions apply between the person (&quot;Participant&quot;) named in the agreement (&quot;Participant Agreement&quot;) and ANFA TRAINING. These terms and conditions are an integral part of the Participant Agreement. In addition to the Participant Agreement, the Participant is also bound by special conditions that may apply to other services and offers at any time. These terms and conditions are available on our website. The agreement comes into force automatically when the Participant has booked and paid for a training session with ANFA TRAINING. When booking and paying, the general terms and conditions, the terms of purchase and the right of withdrawal can be read. In some cases, a physical agreement may need to be signed as with the PT 12 week program.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>PARTICIPATION IN ANFA TRAINING</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>2.1. Participation in ANFA TRAINING can be done by persons of legal age who:</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>2.1.1. Has a generally good state of health where, according to ANFA TRAINING&#x27;s assessment, there is no obvious risk to the person&#x27;s health and/or injury.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>2.1.2. Does not have an outstanding debt in connection with previous participation in ANFA TRAINING.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>2.1.3. Not previously been banned from one or more ANFA TRAINING training sessions.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>2.1.4. Has not behaved reprehensibly in connection with previous participation in ANFA TRAINING.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>2.2.1 Persons who are not of legal age can participate in ANFA TRAINING provided that a guardian signs the agreement. The guardian becomes legally responsible for the participant and is held responsible for all payments in connection with the participation.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>2.2.2 The participant can, if ANFA TRAINING deems it necessary, be assigned a participant card at ANFA TRAINING. The participant card is the property of ANFA TRAINING and is personally disposed of by the participant. The card cannot be transferred or lent. The card must be returned or destroyed by the participant without delay at the end of participation in ANFA TRAINING.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>2.2.3. When registering, a photo of the participant may be taken.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>2.2.4. Participation is valid from the start date and time specified when booking and purchasing training sessions.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>2.5. Purchased training sessions are personal and cannot be transferred or used by anyone other than the participant.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>2.6. ANFA TRAINING regarding participation, concepts and additional services on each occasion with associated descriptions and prices can be found on our website.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>2.7. ANFA TRAINING cannot always guarantee available space at training activities or similar where the number of participants or access is limited.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>2.8. To the extent possible, ANFA TRAINING adapts offers and training times for e.g. PT and Boot camps at available training facilities. The training center in question may be closed or have a reduced offer in connection with e.g. holidays, maintenance work and Force majeure (as defined in clause 6.1).</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>2.9. DISCOUNTS</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>2.9.1. Student discount is given according to agreement between the participating student and ANFA TRAINING.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>2.10. BUSINESS</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>2.10.1. Standard business agreement. Companies can according to increase. With ANFA TRAINING, sign an agreement for individual group training sessions with a personal trainer for up to a maximum of 20 participants at a physical training facility, or the number of participants according to increase. During outdoor training. ANFA TRAINING&#x27;s general conditions apply to each participant in the company agreement. The company that hired ANFA TRAINING is invoiced with 30 days net and 21% late payment interest per month. The company that has signed an agreement with ANFA TRAINING for group passes undertakes to pay for booked group passes if cancellation is not made no later than 48 hours before. The company undertakes to pay the amount according to increase. for the group asset, regardless of whether the number of participants at the start of the group asset is less than intended in case of increase.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>2.10.2. ANFA TRAINING is not responsible for obstacles or limitations that reduce ANFA TRAINING&#x27;s training offer to the Companies and its participants, when the situation is beyond ANFA TRAINING&#x27;s control and ANFA TRAINING could not foresee or counteract the consequences of the situation (Force majeure).</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>PARTICIPANT&#x27;S RESPONSIBILITY</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>3.1. The participant is obliged to:</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>3.1.1. Familiarize yourself with and follow ANFA TRAINING&#x27;s currently applicable safety and well-being rules (general), safety and well-being rules and other rules/guidelines that can be found on our website.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>3.1.2. Inform ANFA TRAINING when changing contact details/payment details, including changes to name, address, e-mail address, telephone number, account number and other relevant information. The report must be submitted without undue delay.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>3.1.3. Show confirmation of payment for the booked training session on arrival at the training center before the participant is allowed to participate. ANFA TRAINING may require the Participant to show identification.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>3.2. Loss of the Participant Card must be reported to ANFA TRAINING as soon as possible. ANFA TRAINING then blocks the card and issues a new one. When a new participant card is issued, the Participant may be obliged to pay a fee to ANFA TRAINING according to the prices applicable at the time.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>3.3. The Participant is responsible for storing the Participant Card in such a way that it is not misused by others. Suspicions of abuse must be reported to ANFA TRAINING as soon as possible.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>PERSONAL DATA, MARKETING AND COMMUNICATION</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>4.1. ANFA TRAINING always processes the Participant&#x27;s personal data in accordance with our privacy policy and current legislation.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>4.2. The Participant agrees that ANFA TRAINING and other companies that are part of the same group register, store and use information about the Participant (name, social security number, address, e-mail address, photo, payment details and the like) and the Participant&#x27;s use of ANFA TRAINING&#x27;s services, for administration and including informing about services from ANFA TRAINING. Data processing manager for the data is ANFA TRAINING&#x27;s CEO.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>4.3. Data cannot be disclosed to third parties without the Participant&#x27;s written consent, unless the disclosure is confidential by law or is part of payment collection, insurance claims or accounting processing.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>4.4. The Participant gives his consent to ANFA TRAINING being able to use all forms of communication with the Participant, including electronic communication (e-mail, SMS, MMS etc.) to inform about and/or market its offer according to Section 19 of the Marketing Act. The participant can withdraw their consent to receive marketing communications at any time by contacting ANFA TRAINING.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>4.5. The consent from the Participant regarding the above points applies as long as the Participant has not withdrawn his consent or has not participated in ANFA TRAINING&#x27;s training sessions or used its services for 6 months from the last occasion.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>4.6. General information from ANFA TRAINING regarding the Participant is primarily sent to the e-mail address or postal address that the Participant has provided.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>PERSONAL INJURIES, STORAGE AND THEFT LIABILITY</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>5.1. The participant always trains under his own responsibility. ANFA TRAINING is not responsible for personal injuries that the Participant may incur in connection with the stay/exercise of activity during training sessions held by ANFA TRAINING. The corresponding limitation of liability applies to other training offers and services/consultants under the auspices of ANFA TRAINING.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>5.2. When storing personal belongings in lockers at facilities, the Participant is responsible for using his own lock and other necessary equipment for safe storage. If the Participant forgets belongings stored in the lockers at one of the facilities ANFA TRAINING&#x27;s training session takes place, the rules and regulations for that facility apply. ANFA TRAINING cannot be held responsible for any loss of such belongings, not even during the mentioned period.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>5.3. ANFA TRAINING is not responsible for theft or loss in any other way of the Participant&#x27;s personal belongings that the Participant brings to ANFA TRAINING&#x27;s training sessions. This applies regardless of whether the belongings are locked in an ordinary wardrobe, safe or similar.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>LIMITATION OF LIABILITY, CHOICE OF LAW, DISPUTES AND JURISDICTION</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>6.1. ANFA TRAINING is not responsible for obstacles or limitations that reduce ANFA TRAINING&#x27;s training offer to the Participant, when the situation is beyond ANFA TRAINING&#x27;s control and ANFA TRAINING could not foresee or counteract the consequences of the situation (Force majeure).</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>6.2. The participant agreement is subject to Swedish law.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>6.3. Disputes between the Participant and ANFA TRAINING shall be tried to be resolved amicably. If this does not lead to a solution, the Participant can take the matter to the General Complaints Board, provided that the board can hear the dispute. Each of the parties still has the right to take the dispute to the ordinary courts.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>6.4. In the event of discrepancies between the English and Swedish versions of the Participant Agreement, the latter shall always take precedence.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>PERSONAL TRAINING TERMS</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>7.1. The owner is responsible for ensuring that his/her state of health is such that training can take place without risk.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>7.2. ANFA TRAINING PTs are 60 minutes long.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>7.3. The agreement is valid for 12 months from the time of sale.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>7.4. A cooling-off period of 14 days applies when purchasing ANFA TRAINING PT.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>7.5. ANFA TRAINING does not refund paid and booked PT hours except on occasions where the holder has canceled according to the terms for personal training.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>7.6. Cancellation by the owner must take place no later than 24 hours before the appointed time. Otherwise, the holder is charged for the time being. Exceptions can be granted by agreement. Does not apply to PT in groups.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>7.7. ANFA TRAINING reserves the right to arrange for a substitute if the personal trainer is not available.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>7.8. If you arrive late for your PT hour, this time will be deducted from the booked time. If your PT is delayed, you will get the corresponding time or time according to increase. on another occasion.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>BOOT CAMP TERMS AND CONDITIONS</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>8.1. The Boot Camp training takes place at the participant&#x27;s own responsibility and risk. The session lasts 35 – 90 minutes with high and low intensity. The participant can assess for himself whether his own general health and level of training is good enough for the training to be carried out without risk of injury and illness. In addition, participants are required to provide the personal trainer with all relevant information about health conditions, previous illness and injury, etc. We expect participants to speak up immediately during training if there are exercises that hurt or cause discomfort. If the participant chooses to train further after the joint training session, this is at their own risk, without ANFA TRAINING and the personal trainer being held responsible for any injuries.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>8.2. The agreement is valid during the period of the Boot Camp for which the participant has registered.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>8.3. The participant has the right to use the right of withdrawal by notifying ANFA TRAINING in writing within 14 days from the date of purchase for the Boot Camp, in accordance with the provisions of the Act on distance contracts and contracts outside business premises. If the right of withdrawal is applied within 14 days after the start of the Boot Camp, no refund will be made.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>8.4. Payment for participation in the Boot Camp applies specifically to the period for which the participant signed up. Participants who make use of the right of withdrawal or are affected by canceled Boot Camp have the right to participate in a new group with a start date up to 12 months after the purchase.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>8.5. ANFA TRAINING does not refund Boot Camp beyond the right of withdrawal (see the applicable General Terms and Conditions for membership in ANFA TRAINING).</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>8.6.Boot Camp 4V. includes 12 times 30 – 90 minutes of training with a personal trainer in a group of up to 20 people.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>8.7.Boot Camp must be carried out according to the plan decided by ANFA TRAINING on each specific training occasion.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>8.8. Boot Camp will in most cases take place in the premises ANFA TRAINING uses or in their immediate vicinity, for example outdoor environments on running tracks or in parks, etc. Unless otherwise agreed.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>8.9. The participant must follow the fixed weekly time decided by the times that ANFA TRAINING set up for the specific Boot Camp occasion. Agreements about other times cannot be made for individual participants.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>8.10. The times for the passes that the Participant has paid for are announced in advance and carried out accordingly. If the Participant is prevented from participating in one or more of the sessions, it is not possible to make good on it/these, even if the Participant reports the prevention in good time or is unable to attend due to illness.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>8.11.If the Participant arrives late to the agreed time for the Boot Camp session, this does not mean that the current training session is extended for the Participant. The training session starts and ends at the agreed time.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>8.12.In special circumstances that cause the personal trainer to be absent (illness etc.), ANFA TRAINING reserves the right to use another personal trainer. If ANFA TRAINING cannot get hold of a new personal trainer and the pass cannot be held according to the agreement, the Participant will receive the pass. Passes held by the Participant must be completed at the time specified for the combined group.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>8.13.If a personal trainer for a Boot Camp is late, the participants will have the corresponding time extended on the session in question.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>PERSONAL DATA POLICY</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>This personal data policy provides you with information about how and why we process our members&#x27; personal data and personal data. ANFA TRAINING («Convivencia AB» or «we») operates the ANFA TRAINING training concept. We are the ones responsible for the processing of personal data processed in connection with this activity.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>HOW WE USE PERSONAL DATA</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Administration of Participants. In order to register you as a Participant with us and for us to be able to take payment or invoicing (company), we process personal data such as name, social security number, contact information, picture and your communication with us. If you participate through your employer (ordinary Company Agreement), we will also process information about your employer.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Online training. In order to administer and monitor the use of our web-based services, we will also record your login details (username/password), your searches, your previous recordings and the favorites you save.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>App features. In order to offer relevant functionality, we process information about the use of social functions, your exercise and preference choices that you yourself make in the app. We also use functionality offered by Google or Apple that you choose to activate (for example, localization or Bluetooth).</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Training-related services. If you use our exercise-related services, such as physiotherapy, massage, nutritional advice or lifestyle course, we will process information about you that is necessary for these services, such as health, weight, habits, needs and preferences.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Köp. Om du gör köp i vår online-butik kommer vi av bokföringsskäl att behandla upplysningar om dina köp, dvs. vad du köpte, tidpunkten för köpet samt belopp.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Produktutveckling. För att utvärdera, förbättra och optimera vårt träningsutbud, kommer vi att kunna behandla dina svar på deltagare undersökningar samt analysera statistik över din användning av vårt träningsutbud för att förstå våra deltagares behov och preferenser.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Vi måste ha behandlingsunderlag enligt Dataskyddsförordningen (GDPR) för vår behandling av personuppgifter. För administration av deltagande, träningsuppföljning, online träning, app-funktioner och träningsrelaterade tjänster är behandlingsunderlaget att det är nödvändigt för att uppfylla vårt avtal med dig. För köp är det nödvändigheten av att uppfylla en juridisk förpliktelse. För produktutveckling är det vårt berättigade intresse gällande förbättring och innovation. Om det är nödvändigt för oss att behandla särskilda kategorier av personuppgifter (känsliga personuppgifter) för att utföra våra tjänster till dig, är behandlingsunderlaget ditt godkännande som du ger via de allmänna villkoren (Dataskyddsförordningen (GDPR) artikel 6 nr. 1 bokstav a och artikel 7 nr. 4).</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Vi kan även komma att behandla personuppgifter för andra syften och ändamål, om du godkänner det. I sådana fall kan du när som helst annullera ditt godkännande.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Vi kan dessutom behöva behandla personuppgifter för andra förenliga syften och ändamål, exempelvis för bokföring, vid hantering av tvistemål och rättssaker samt vid uppköp, fusioner eller liknande transaktioner och ärenden.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>HOW WE CARRY OUT MARKETING</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>We want to keep our participants updated about our services and provide great offers. From time to time we will therefore send you newsletters and marketing, for example via e-mail. We will be able to adapt such communication based on where or what you have been training, so that it is more relevant to you. If you no longer wish to receive marketing and newsletters from us, you can use the unsubscribe link in the marketing communications you receive or through our website. Please note that you cannot unsubscribe from the sending of non-marketing information.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>HOW WE PROCESS INFORMATION ON SOCIAL MEDIA</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>If you visit our social media pages, we will be able to see your reactions (uploads, likes, comments, etc.). We will also have access to anonymized statistics in order to gain knowledge about the use of our pages on social media. For processing such information, we have processing responsibility with the social media. The basis for our processing of any personal data in connection with this is our legitimate interest in having a page on the social media and in having knowledge of how it is used. Please note that even if you delete your account or stop following us on the social media, your reactions (uploads, likes, comments, etc.) will still be available on our site.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>WHO WE SHARE PERSONAL DATA WITH</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>We will treat your personal data confidentially. However, we must share personal data with other businesses in order to carry out the functions and purposes described above in a good way:</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Suppliers. We share information with suppliers who help us perform our services, for example IT suppliers.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>We may also share information with authorities if we are required to do so. We may also share information about you with others if you agree.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>HOW LONG DO WE SAVE THE PERSONAL INFORMATION</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>We save information about you as long as it is necessary for the purposes mentioned above. Then we delete them. Unless you agree otherwise, this essentially means that:</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Information about the administration of participation is deleted no later than 6 months after the last participation or service was used.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Information about training history and information about online training is deleted no later than 6 months after the membership has ended.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Information about self-training in the app is deleted when you yourself request it, but no later than 6 months after the membership has ended. We do not save location data beyond session termination.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Information about training-related services is deleted on an ongoing basis.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Information about purchases is deleted after 5 years in accordance with the Accounting Act.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Information used for product development is deleted by anonymizing the information as soon as possible.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Information used for recruitment to studies is deleted shortly after the recruitment has been completed.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>We can choose to anonymize the information instead of deleting it, i.e. that we save the information, but that it is no longer possible to link it to you as an individual</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>YOUR PRIVACY AND PERSONAL DATA RIGHTS</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>You have several rights according to the personal data and privacy protection regulations. You have, among other things, the right to demand access, correction, deletion, limitation, data porting and to object to our processing of information about you. Contact us if you want to exercise your rights. We will respond to your message as soon as possible, usually within one month at the latest. Please note that there are several exceptions and limitations to these privacy protection and personal data rights that may prevent us from needing or allowing you to exercise these rights.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>If you disagree or are dissatisfied with the way in which we process your personal data, you can submit a complaint to the Swedish Data Protection Authority. We appreciate it if you contact us first, so we can clear up any misunderstandings.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>You can contact info@anfatraining.com if you want to exercise your privacy protection rights or if you have other questions, comments or if you want more information about our processing of personal data.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Cookies Our website uses cookies. You can find more information about this in our cookie policy.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Changes We will be able to update this personal data policy as necessary, for example when we launch new products or make changes to existing products. You will receive information from us if we make material changes. You will always find the latest version of the personal data policy on our website.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>COOKIE POLICY</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Here you will find information about how ANFA TRAINING (&quot;Convivencia AB&quot; or &quot;we&quot;) uses information capsules/cookies, pixels and similar technologies (collectively called &quot;cookies&quot;) on our website sats.no.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>WHAT ARE COOKIES?</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Cookies: Small text files that are saved on your device (mobile phone, tablet, computer) to identify your browser. Cookies can either be delivered by us (first-party cookies) or by other actors (third-party cookies).</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Pixels (Pixel tags): Image files that are used to connect you to a third-party website, including to activate cookies from the third-party website. A pixel can read and write to cookies stored on your device.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Scripts: Snippets of code necessary to activate a pixel or used to identify your browser or device across different web visits and web pages.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>WHAT WE USE COOKIES FOR</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>We use cookies on our website for the following purposes and purposes:</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Necessary cookies, i.e. cookies that are necessary for our website to be in operation.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Cookies for activity, i.e. which helps to measure visitor traffic regarding our website.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Cookies for functionality, i.e. which contributes to improved functionality and customization on our website.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Cookies for targeted advertising, i.e. ads that help appear as relevant ads on other websites based on your navigation on our website.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>WHAT COOKIES WE USE</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>In the cookie banner on our website, we show a list of the cookies that are always used on our website. There we also provide information about name, host computer, duration, type, category and description. If you want to see such information, but do not get the cookie banner because you have previously visited our page, you can go in and change the information settings.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Please be aware that our website may display, use or link to content on other people&#x27;s websites, which may result in third-party cookies being stored on your device. This can happen, for example, if you navigate from Facebook to our website. You will find more information about this in the personal data policy of the relevant third party actors.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>YOUR CHOICES</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>You can choose whether you want to accept or reserve against the use of cookies via settings in your browser. Here you will find more information on how to make settings for the most common browsers: Internet Explorer, Mozilla Firefox and Google Chrome.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>You can also choose which cookies you want to accept or opt out of in the cookie banner on our website.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>If you opt out of the use of cookies, you may experience that our website does not function optimally.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Personal data protection</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>We do not normally link cookies to you as a person. However, it may happen that you are or may be identified indirectly, for example if you log in to our website. In such cases, we may connect cookies with other information we have regarding your customer relationship, in order to provide you with a more customized user experience on our website. For further information, see our personal data policy.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Changes</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>We may update this cookie policy as necessary, for example if we make changes to our website. You will receive information from us if we make material changes. You will always find the latest version of the cookie policy on our website.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Photography &amp; Social Media</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>ANFA TRAINING takes pictures during the training sessions that are published on social media such as Facebook, Instagram and also the Anfa Training website. The images can also be used for other marketing purposes. If you do not want pictures of you to appear on our social media - let us know as soon as possible.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>The information you provide, as well as information about services/goods, is limited to what is necessary to enter into a contractual relationship with Anfa Training. Read more about this in our Data Protection Policy.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>BOOKING RULES</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Group training</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>The booking is binding but can be refunded if cancellation takes place no later than 24 hours before the booked training session has started.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>The participant&#x27;s place is only guaranteed after the participant has received a confirmation and that the fee has been paid according to the conditions stated in the received confirmation.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Paid registration fee is not refunded in the event of absence/dropout during an ongoing training session.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Your place at the training is personal and cannot be used by anyone else.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>The booking only applies to the selected location, day and time.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Personal Training &amp; Coaching</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>The PT training is personal and cannot be used by anyone else.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Cancellation takes place no later than 24 hours before. In case of no-show, the full amount will be charged.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Payment made is not refunded.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Canceled Passports</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>The training takes place regardless of the weather, if it does not pose a risk to the participants, for example thunderstorms. If training is cancelled, participants will be notified via email or social media.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>If there are too few registrations, the training for that period may be cancelled. We will then refund the registration fee.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>In case of illness, a pass can be cancelled. All participants will then be notified no later than 3 hours before the session.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>In the event of a session canceled by the instructor, due to illness or other circumstances, the participant is compensated with a new pass at another time within 12 months.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>TERMS OF PURCHASE</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Participation in ANFA TRAINING training sessions</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Group training</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>To train with ANFA TRAINING, the participant must be 18 years old. If the participant is younger than 18 years, but at least 14 years old, the guardian&#x27;s consent is required.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>When registering, state the child&#x27;s name and social security number as well as contact details with telephone number, social security number and address for the guardian.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>State of health, Accidents and Property</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Participation is at your own risk and it is recommended to review your accident insurance.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Participants are not insured by ANFA TRAINING.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>ANFA TRAINING is not responsible under any circumstances for illness or injuries that occur in connection with or as a result of participation in the training.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>The participant is responsible for ensuring that the health condition is such that the participant can participate in the training without risk.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>The participant is responsible for appropriate clothing and any damage to clothing, shoes or other equipment that the participant uses during the training sessions.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>ANFA TRAINING is not responsible for losses due to theft, burglary or for any other reason.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>RIGHT OF CANCELLATION/RETURN</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Right of withdrawal when purchasing on the internet – You as a private person have the right, according to the Distance Contracts Act (2005:59), to withdraw or complain about your purchase within 14 days after you received the item/made your exercise notification (the withdrawal period). If you regret your purchase, it is important that you contact us via the contact form on the website. Note. we do not trigger complaints locally in individual locations or via our instructors.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>The right of withdrawal only applies to unused goods in the original box and with labels remaining. When registering for a training session, the right of withdrawal only applies if the training session or Bootcamp has not started. Gift cards and processed products such as printed clothing and sale items cannot be returned. These are not included in open purchase.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>When exercising the right of withdrawal, the item must be returned/sent back to Anfa Training within 14 days of receiving the item. The buyer is responsible for the return cost. The product was returned to the address: (For Morocco) Anfa Training S.A.R.L 12 rue Saria Ben Zounaim, etg. 3 appt 3, Palmier Casablanca Morocco. (For Europe) Anfa Training C/O Soleus Invest Travessera De Gracia 278, local 5, 08025 Barcelona Spain.</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>-</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>Reimbursement is made without delay and no later than 30 days after the buyer&#x27;s notification that the contract has been withdrawn, provided that ANFA TRAINING has received the goods in return, or a receipt that the goods have been sent back within the cancellation period (14 days).</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>COMPLAINT</p>
            <p style={{ color: "var(--text-muted)", fontSize: "15px", lineHeight: "1.7", marginBottom: "16px" }}>In the event of a complaint, the item is returned to the above address. Put a note in the package with what is wrong with the item and your address. ANFA TRAINING is responsible for all shipping costs and replaces the item in the event of a fault.</p>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
